spring.application.name=TrackAssets

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_trackassets?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# API KEY
alpha.vantage.api.key=7M89TD8HTC47BV5J